### PR TITLE
Ft user login 161114065

### PR DESCRIPTION
**Pull request by koitoror**
**What is this PR?**
This is a pull request on discusion about a user login page User Interface(UI). It helps users to redirect them to specific pages.
_Like an admin(store manager) will be redirect to admins page after login_

**Technologies I have Used so far**

HTML for markup of the elements
CSS for styling of the login elements
A Screen shot of the login have designed

login

### CODE REVIEW

**Comment by Nicanor008** [comment]
The UI is dope Dan, I like the modal pop on how you have designed. One thing though, I think you should not have a remember me the option for app security purposes

**Comment by Nicanor008** [comment]
Great work here

**Comment by koitoror** [comment]
thanks for the prompt feedback @Nicanor008 let me implement , a i thought remember-me 
is a standard feature in a login page

**Comment by kamaudan** [comment]
Looking good, I will also use a modal

**Comment by Nicanor008** [comment]
Also is the cancel button rightly placed, what if it could be Close( that is close the modal)

**Comment by Nicanor008** [comment]
@koitoror yea it is, was just thinking about it in this app. As in there can be many attendants using the same computers for shift purposes(night/day). So I don't want to be login in 24hrs

**Comment by koitoror** [comment]
@Nicanor008 its not login 24hrs - i've actually pressed the modal on the landing page otherwise its the plain landing page visible in the translucent background

**Pull request merged**
